//! `wm-burst provision` — generate and apply an Ansible playbook to converge
//! a fresh host to builder-ready (pinned 1.85+1.88 toolchains, sccache, shared-cache creds).

use anyhow::{Context, Result};
use clap::Args;

use crate::config::Config;

/// Arguments for `wm-burst provision`.
#[derive(Args, Debug)]
pub struct ProvisionArgs {
    /// Path to config file (default: ~/.config/wm-burst/config.toml).
    #[arg(long)]
    pub config: Option<std::path::PathBuf>,

    /// Only generate the playbook; do not run ansible-playbook.
    #[arg(long)]
    pub generate_only: bool,

    /// ansible-playbook --check (dry-run); do not make any changes.
    #[arg(long)]
    pub check: bool,

    /// Write generated playbook to this path (default: /tmp/wm-burst-provision.yml).
    #[arg(long, default_value = "/tmp/wm-burst-provision.yml")]
    pub playbook_path: std::path::PathBuf,
}

/// Run the `provision` subcommand.
///
/// # Errors
/// Returns an error if the config is missing, the playbook cannot be written,
/// or ansible-playbook exits non-zero.
pub fn run(args: &ProvisionArgs) -> Result<std::process::ExitCode> {
    let config_path = match &args.config {
        Some(p) => p.clone(),
        None => Config::default_path()?,
    };
    let cfg = Config::load(Some(&config_path))?;
    cfg.validate()?;

    let playbook = generate_playbook(&cfg);
    std::fs::write(&args.playbook_path, &playbook)
        .with_context(|| format!("cannot write playbook to {}", args.playbook_path.display()))?;
    eprintln!("playbook written to {}", args.playbook_path.display());

    if args.generate_only {
        println!("{playbook}");
        return Ok(std::process::ExitCode::SUCCESS);
    }

    let mut cmd = std::process::Command::new("ansible-playbook");
    cmd.arg(&args.playbook_path)
        .args(["-i", &format!("{},", cfg.remote_host)]);

    if args.check {
        cmd.arg("--check");
        eprintln!("[provision] dry-run mode (--check)");
    }

    eprintln!("[provision] running ansible-playbook against {} ...", cfg.remote_host);
    let status = cmd.status().context("failed to run ansible-playbook; is ansible installed?")?;

    if status.success() {
        println!("[provision] host {} is ready", cfg.remote_host);
        Ok(std::process::ExitCode::SUCCESS)
    } else {
        Err(anyhow::anyhow!(
            "ansible-playbook exited {status}; check output above for details"
        ))
    }
}

/// Generate the idempotent Ansible playbook content.
///
/// Installs rustup + 1.85 + 1.88 toolchains, sccache, build deps, and
/// configures the shared-cache credentials.
#[must_use]
#[allow(clippy::too_many_lines)] // playbook template is intentionally verbose
pub fn generate_playbook(cfg: &Config) -> String {
    let access_key = cfg
        .sccache
        .access_key
        .as_deref()
        .unwrap_or("CHANGE_ME_ACCESS_KEY");
    let secret_key = cfg
        .sccache
        .secret_key
        .as_deref()
        .unwrap_or("CHANGE_ME_SECRET_KEY");

    // Build the playbook by string concatenation to avoid conflict between
    // Rust's format!() `{var}` syntax and Ansible's Jinja2 `{{ var }}` syntax.
    let av = "{{ ansible_user }}";  // Ansible Jinja2 variable reference
    let av_item = "{{ item }}";
    let av_toolchains = "{{ rust_toolchains }}";
    let av_mark = "# {mark} wm-burst sccache config";
    let av_sccache_endpoint = "{{ sccache_endpoint }}";
    let av_sccache_bucket = "{{ sccache_bucket }}";
    let av_sccache_access = "{{ sccache_access_key }}";
    let av_sccache_secret = "{{ sccache_secret_key }}";
    let av_toolchain_stdout = "{{ toolchain_list.stdout }}";

    let mut s = String::new();
    s.push_str("---\n");
    s.push_str("# wm-burst provision playbook — generated by `wm-burst provision --generate-only`\n");
    s.push_str("# Idempotent: safe to re-run. Converges a fresh host to builder-ready.\n#\n");
    s.push_str("# Toolchains installed: 1.85.0 + 1.88 (matching this repo's split).\n");
    s.push_str(&format!("# sccache endpoint: {}\n", cfg.sccache.endpoint));
    s.push_str(&format!("# sccache bucket:   {}\n\n", cfg.sccache.bucket));
    s.push_str("- name: Provision wm-burst builder host\n");
    s.push_str("  hosts: all\n");
    s.push_str("  become: true\n");
    s.push_str("  gather_facts: true\n\n");
    s.push_str("  vars:\n");
    s.push_str("    rust_toolchains:\n");
    s.push_str("      - \"1.85.0\"\n");
    s.push_str("      - \"1.88\"\n");
    s.push_str(&format!("    sccache_endpoint: \"{}\"\n", cfg.sccache.endpoint));
    s.push_str(&format!("    sccache_bucket:   \"{}\"\n", cfg.sccache.bucket));
    s.push_str(&format!("    sccache_access_key: \"{access_key}\"\n    sccache_secret_key: \"{secret_key}\"\n\n"));
    s.push_str("  tasks:\n");
    s.push_str("    - name: Install build dependencies (Debian/Ubuntu)\n");
    s.push_str("      ansible.builtin.apt:\n");
    s.push_str("        name:\n");
    s.push_str("          - build-essential\n");
    s.push_str("          - pkg-config\n");
    s.push_str("          - libssl-dev\n");
    s.push_str("          - curl\n");
    s.push_str("          - git\n");
    s.push_str("          - unzip\n");
    s.push_str("        state: present\n");
    s.push_str("        update_cache: true\n");
    s.push_str("      when: ansible_os_family == \"Debian\"\n\n");
    s.push_str("    - name: Install build dependencies (Arch/Manjaro)\n");
    s.push_str("      community.general.pacman:\n");
    s.push_str("        name:\n");
    s.push_str("          - base-devel\n");
    s.push_str("          - openssl\n");
    s.push_str("          - curl\n");
    s.push_str("          - git\n");
    s.push_str("        state: present\n");
    s.push_str("      when: ansible_os_family == \"Archlinux\"\n\n");
    s.push_str("    - name: Check if rustup is installed\n");
    s.push_str("      ansible.builtin.stat:\n");
    s.push_str(&format!("        path: \"/home/{av}/.cargo/bin/rustup\"\n"));
    s.push_str("      register: rustup_stat\n");
    s.push_str("      become: false\n\n");
    s.push_str("    - name: Install rustup\n");
    s.push_str("      ansible.builtin.shell: |\n");
    s.push_str("        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path\n");
    s.push_str("      become: false\n");
    s.push_str("      when: not rustup_stat.stat.exists\n");
    s.push_str("      args:\n");
    s.push_str(&format!("        creates: \"/home/{av}/.cargo/bin/rustup\"\n\n"));
    s.push_str("    - name: Install pinned Rust toolchains\n");
    s.push_str("      ansible.builtin.command:\n");
    s.push_str(&format!(
        "        cmd: \"/home/{av}/.cargo/bin/rustup toolchain install {av_item} --profile minimal --component rustfmt,clippy\"\n"
    ));
    s.push_str(&format!("      loop: \"{av_toolchains}\"\n"));
    s.push_str("      become: false\n");
    s.push_str("      register: toolchain_install\n");
    s.push_str("      changed_when: \"'installed' in toolchain_install.stdout\"\n\n");
    s.push_str("    - name: Check if sccache is installed\n");
    s.push_str("      ansible.builtin.stat:\n");
    s.push_str(&format!("        path: \"/home/{av}/.cargo/bin/sccache\"\n"));
    s.push_str("      register: sccache_stat\n");
    s.push_str("      become: false\n\n");
    s.push_str("    - name: Install sccache\n");
    s.push_str("      ansible.builtin.command:\n");
    s.push_str(&format!("        cmd: \"/home/{av}/.cargo/bin/cargo install sccache\"\n"));
    s.push_str("      become: false\n");
    s.push_str("      when: not sccache_stat.stat.exists\n");
    s.push_str("      args:\n");
    s.push_str(&format!("        creates: \"/home/{av}/.cargo/bin/sccache\"\n\n"));
    s.push_str("    - name: Write sccache environment config\n");
    s.push_str("      ansible.builtin.blockinfile:\n");
    s.push_str(&format!("        path: \"/home/{av}/.bashrc\"\n"));
    s.push_str(&format!("        marker: \"{av_mark}\"\n"));
    s.push_str("        block: |\n");
    s.push_str(&format!("          export SCCACHE_ENDPOINT=\"{av_sccache_endpoint}\"\n"));
    s.push_str(&format!("          export SCCACHE_BUCKET=\"{av_sccache_bucket}\"\n"));
    s.push_str(&format!("          export AWS_ACCESS_KEY_ID=\"{av_sccache_access}\"\n"));
    s.push_str(&format!("          export AWS_SECRET_ACCESS_KEY=\"{av_sccache_secret}\"\n"));
    s.push_str("          export RUSTC_WRAPPER=sccache\n");
    s.push_str("      become: false\n\n");
    s.push_str("    - name: Verify rustc toolchains are installed\n");
    s.push_str("      ansible.builtin.command:\n");
    s.push_str(&format!("        cmd: \"/home/{av}/.cargo/bin/rustup toolchain list\"\n"));
    s.push_str("      become: false\n");
    s.push_str("      register: toolchain_list\n");
    s.push_str("      changed_when: false\n\n");
    s.push_str("    - name: Assert both toolchains present\n");
    s.push_str("      ansible.builtin.assert:\n");
    s.push_str("        that:\n");
    s.push_str("          - \"'1.85' in toolchain_list.stdout\"\n");
    s.push_str("          - \"'1.88' in toolchain_list.stdout\"\n");
    s.push_str(&format!(
        "        fail_msg: \"Expected toolchains 1.85 and 1.88 to be installed. Got: {av_toolchain_stdout}\"\n"
    ));
    s
}
